### ISSUE TITLE
The script doesn't work on Windows 10 latest update at all

### ISSUE THREAD

**Issue by lefthairynut** [pmb6tz/windows-desktop-switcher#103]
Hi. The script doesn't work for me at all on Windows 10 latest update. tried the new dll from [here](https://github.com/Ciantic/VirtualDesktopAccessor/releases) with no avail. I didn't change a keybinding or add anything to the script i'm using it fresh out of clone. The script captures the keybindings but the functions binded to the keybindings doesn't seem to work at all.

**Comment by lefthairynut** [comment]
Ok. There is a separate dll for Windows 10. I didn't delete the the post for others that may encounter the same problem.[ dll for Windows 10](https://github.com/Ciantic/VirtualDesktopAccessor/releases/download/2019-windows10/VirtualDesktopAccessor.dll)

**Comment by Elijas** [comment]
I'll close it but pin it to make it easily discoverable. Thanks!
