### ISSUE TITLE
Reduce animation

### ISSUE THREAD

**Issue by petrklus** [pmb6tz/windows-desktop-switcher#12]
First of all, thank you for great piece of work!

However, I am often using 10+ task views (crazy, right?) and switching between them becomes a bit nauseating experience (especially going from 1 to 10). Is there any way to just go "straight" to the desktop without going through all of the other ones?

**Comment by Perlence** [comment]
Hello @petrklus!

Did you try to disable window animations?

> Control panel → System → Advansed system settings → Performance settings. Uncheck "Animate windows when minimizing and maximizing".
> — http://superuser.com/a/1058350/547530

There's also another method of switching desktops that I mentioned in https://github.com/pmb6tz/windows-desktop-switcher/issues/8#issue-162347132, maybe you can try it and see if it's less painful for eyes :grimacing:

**Comment by pmb6tz** [comment]
I wonder if we could use @Perlence method for when the target desktop is >2 away, and anything less would use the mechanism in place right now. Wouldn't be hard to do.. Thoughts?

**Comment by Perlence** [comment]
@petrklus @pmb6tz Just pushed a branch [`hybrid-switching`](https://github.com/pmb6tz/windows-desktop-switcher/tree/hybrid-switching). Feel free to experiment with it!

**Comment by Perlence** [comment]
@petrklus On a side note, if you have 10+ task views, how do you access them? I mean, what key mappings do you use then?

**Comment by petrklus** [comment]
@Perlence thank you, will try the new branch! 

Speaking of hot keys for 10+ desktop - on my mac, I just have another modifier that I add (for example, 1 is CTRL+1 and 11 is CTRL+ALT+1). I have then replicated the same setup by modifying your script

**Comment by Perlence** [comment]
@petrklus I see, clever.

**Comment by petrklus** [comment]
@Perlence I've tested the branch but it does not seem to be working very well for me - sometimes it does, sometimes it does not switch the desktop and crashes explorer.

I was wondering - I am a complete novice when it comes to AHK but does it support calling windows apis?

For example: http://stackoverflow.com/questions/30487556/detecting-active-virtual-desktop-on-windows-10-task-view-virtual-desktop-swi

Especially info from http://www.cyberforum.ru/blogs/105416/blog3671.html

**Comment by Perlence** [comment]
@petrklus There's [`DllCall`](https://autohotkey.com/docs/commands/DllCall.htm) function. I've also seen some AHK wrappers around said library, but they didn't work for me. This method kind of depends on "private" API and there's no way it will remain stable in the future.

> it does not seem to be working very well for me - sometimes it does, sometimes it does not switch the desktop and crashes explorer.

Can you start [DebugView](https://technet.microsoft.com/en-us/sysinternals/debugview.aspx) and inspect its output?

**Comment by pmb6tz** [comment]
I've merged PR #20 recently which does reduce window animation significantly by integrating a new DLL. Give that a shot maybe (if you're still using this years later)!

**Comment by Elijas** [comment]
@pmb6tz You might also want to delete this branch since it is from this closed issue https://github.com/pmb6tz/windows-desktop-switcher/tree/hybrid-switching

The solution fixes the issue by defocusing active windows, which is already done.

It's a cool solution nevertheless, props to Perlence! :)
