### ISSUE TITLE
Capslock - actually stays locked

### ISSUE THREAD

**Issue by AKAlias** [pmb6tz/windows-desktop-switcher#16]
Hi!

First off: thanks! Your script is great. But I figure something is still not quite in place as sometimes (but lately more often) capslock actually stays locked after using it. 

Is there someway to heal this issue? 

Using ALT does not really pose as an alternative as it is not a as convenient hotkey. 

I appreciate any help!

Thanks

**Comment by Perlence** [comment]
Hey, I use <kbd>Alt</kbd> as modifier, and I actually noticed that it sometimes gets stuck too.

**Comment by AKAlias** [comment]
Have you by any chance found a way to solve this problem? It happens to me actually quite ofte. Around 50% of the time.

**Comment by Perlence** [comment]
I switched to https://github.com/sdias/win-10-virtual-desktop-enhancer just to check it out and it stuck with me. I still encounter the issue even there but very, very rarely.

**Comment by AKAlias** [comment]
Thanks for your input. It really seems to work well. I assume you never tried it with Capslocks, right?

**Comment by Perlence** [comment]
No problem! No, I didn't try setting Caps Lock.

**Comment by AKAlias** [comment]
Okay, big thanks anyway. I am now using the other script as well with ALT and it works great. You made my day!

**Comment by pmb6tz** [comment]
I deprecated this tool in favor of the one @Perlence linked--a few months ago I added a note to the top of the readme to send people to that, but I'm sure not everyone notices... :-) The new tool is simply better--it's calling native DLL's which weren't available when I wrote this one.
