### ISSUE TITLE
The  button '3' does not working when script is running?

### ISSUE THREAD

**Issue by AzyCrw4282** [pmb6tz/windows-desktop-switcher#21]
For some reason whenever I have the script running the button '3' is not working. 
The button on the num pad is working but the other one is not. Is this a bug?

**Comment by AzyCrw4282** [comment]
Issue fixed. Just had to modify some of the code.

**Comment by derpsteb** [comment]
What modifications did you do?

**Comment by AzyCrw4282** [comment]
way too long now to remember. i am pretty sure it was being overridden elsewhere and i had to slightly modify the AutohotKey code
