### ISSUE TITLE
Suggestion: Add a hotkey to cycle through all desktops.

### ISSUE THREAD

**Issue by Muldfox** [pmb6tz/windows-desktop-switcher#22]
Thanks for this amazing script, much appreciated.

I would however love to see a feature where you cycle through all the windows with just one hotkey, for example windows key + tab (although that example, specifically, is used for that stupid virtual desktop overview that Microsoft added).

So if you have lets say three virtual desktops, when you are cycling through them with the new hotkey, when reaching the last desktop, if you were to click the cycle button again you would go back to the first desktop.

Thanks again!

Edit: I made my own solution, but I see that you already created a pull request. Although I don't need it now, I think others might find it useful.

**Comment by Elijas** [comment]
1. You can already cycle with one key by using , as you can see in this file: 

There is already this functionality, you can see it in this file: https://github.com/pmb6tz/windows-desktop-switcher/blob/4118c9d8a074c556cca9f35efc86fb4c69a67d88/desktop_switcher.ahk#L184

For example you can press `^!n` to switch to the next desktop. (`^` means `Ctrl`, `!` means `Alt`)

Other options are:
```
CapsLock & n::switchDesktopByNumber(CurrentDesktop + 1)
CapsLock & p::switchDesktopByNumber(CurrentDesktop - 1)
CapsLock & s::switchDesktopByNumber(CurrentDesktop + 1)
CapsLock & a::switchDesktopByNumber(CurrentDesktop - 1)
```
```
^!n::switchDesktopByNumber(CurrentDesktop + 1)
^!p::switchDesktopByNumber(CurrentDesktop - 1)
^!s::switchDesktopByNumber(CurrentDesktop + 1)
^!a::switchDesktopByNumber(CurrentDesktop - 1)
```

There are also hotkeys for creating/deleting desktops on the fly (`c`, `d`)

2. Regarding cycling, I'll create a pull request, it's really easy to implement

**Comment by Elijas** [comment]
I've implemented with https://github.com/pmb6tz/windows-desktop-switcher/pull/23 the cycling switching, you can download the updated program here: https://github.com/Elijas/windows-desktop-switcher

**Comment by pmb6tz** [comment]
Accepted PR #23 to address this; closing this issue as completed.
