### ISSUE TITLE
[minor] Possible future bug fixes

### ISSUE THREAD

**Issue by Elijas** [pmb6tz/windows-desktop-switcher#25]
When reading the [docs ](https://github.com/Ciantic/VirtualDesktopAccessor/blob/master/README.markdown) about the dll that is used here, I've noticed that there is one helper function that should probably be in this repo too. But I haven't noticed any bugs myself that would require this, though, so I won't submit a PR just yet.

```
RestartVirtualDesktopAccessorProc := DllCall("GetProcAddress", Ptr, hVirtualDesktopAccessor, AStr, "RestartVirtualDesktopAccessor", "Ptr")

; Restart the virtual desktop accessor when Explorer.exe crashes, or restarts (e.g. when coming from fullscreen game)
explorerRestartMsg := DllCall("user32\RegisterWindowMessage", "Str", "TaskbarCreated")
OnMessage(explorerRestartMsg, "OnExplorerRestart")
OnExplorerRestart(wParam, lParam, msg, hwnd) {
    global RestartVirtualDesktopAccessorProc
    DllCall(RestartVirtualDesktopAccessorProc, UInt, result)
}
```

There are other useful functions such as a Hook that will execute right after a desktop switch event, even when desktop is not switched with the script. Also there are functions `GoToDesktopNumber`, `GetCurrentDesktopNumber`, etc that may or may not work better than the current ones.

**Comment by Elijas** [comment]
This doesn't deserve creating a separate issue, but there might be some speed/stability gains by avoiding all of the other code (esp. `WinActivate, ahk_class Shell_TrayWnd`) when switching to an adjacent desktop.

```
    if (_CurrentDesktop + 1 = targetDesktop) {
    	Send, ^#{Right}
    	return
    }
    if (_CurrentDesktop - 1 = targetDesktop) {
    	Send, ^#{Left}
    	return
    }
```

**Comment by pmb6tz** [comment]
Yep - the DLL was only recently added so there are definitely aspects of it that we could be leveraging (but aren't). Some of the value of this script was precisely that we didn't use the DLL, but if people really want that we can just maintain a fork that doesn't rely on it. For now, I think considering improvements like this is fine and makes sense.

**Comment by Elijas** [comment]
I've checked `GoToDesktopNumber` from the DLL, and it worked worse than our current solution. When switching between desktops back and forth fast, it doesn't switch sometimes.

**Comment by pmb6tz** [comment]
Wow, that's surprising. Thanks for giving that a look...
