### ISSUE TITLE
Suggestion: Hotkey to toggle window/app presence on all desktops.

### ISSUE THREAD

**Issue by Elijas** [pmb6tz/windows-desktop-switcher#26]
I've implemented this in my own private fork, but don't use it much, so I won't submit a PR. Regardless, I thought that someone might like to see this implemented? Function is already present in the dll, so this could be added with [just a few lines of code](https://github.com/Ciantic/VirtualDesktopAccessor/blob/master/README.markdown).

Although it's probably not essential, so I won't submit a PR just yet, to avoid feature creep :)

**Comment by pmb6tz** [comment]
Let's gauge interest on this one; if we get sufficient interest we can add the change. Otherwise we'll keep it simple for now.

**Comment by Elijas** [comment]
Duplicate of #32
