### ISSUE TITLE
Hotkeys intercepted by cmd windows 

### ISSUE THREAD

**Issue by pmb6tz** [pmb6tz/windows-desktop-switcher#27]
I've noticed that if a command prompt (cmd) window is currently focused, it captures the caps+num sequence, preventing desktop switching entirely. I personally use command windows quite a lot, so I'm adding an item to take a look at this issue.

**Comment by Elijas** [comment]
Quickfix: Just change all "capslock" in the file with "tab", and rerun the script

I don't make claims whether we should or shouldn't change the repo though

**Comment by Elijas** [comment]
Does this still occur with "Run as Administrator"?

**Comment by pmb6tz** [comment]
That's fixed it.

**Comment by Elijas** [comment]
@pmb6tz I've encountered this with terminals too :) Just in case you'd want to run the script as root on boot, Task Scheduler is a nice way

![image](https://user-images.githubusercontent.com/4084885/55994346-18b99a00-5cba-11e9-843a-0c7a2250e242.png)

**Comment by Elijas** [comment]
@pmb6tz I've encountered this with terminals too :) At the risk of stating the obvious, a nice way to silently run the script as root on boot is to make use of the Task Scheduler:
 
![image](https://user-images.githubusercontent.com/4084885/55994599-d775ba00-5cba-11e9-89b5-48447ca2f1bf.png)
