### ISSUE TITLE
Unable to move to other windows.

### ISSUE THREAD

**Issue by NicTanghe** [pmb6tz/windows-desktop-switcher#37]
I can not use caps + azerty to move active windows to another destop.
It simply behaves the same as pressing caps + 1234.

**Comment by Elijas** [comment]
I did not understand the issue. I assume, you are using AZERTY keyboard instead of QWERTY and pressing `Caps + A` does not move the window to the first desktop?

If yes, could you try changing `q` in `CapsLock & q::MoveCurrentWindowToDesktop(1)` ([link](https://github.com/pmb6tz/windows-desktop-switcher/blob/ba8760b015cfeca3b1fc41d92c6a421103f8b89d/user_config.ahk#L43)) to `a`?

**Comment by NicTanghe** [comment]
This is how that part of the user config looks.

``` (ahk)
CapsLock & a::MoveCurrentWindowToDesktop(1)
CapsLock & z::MoveCurrentWindowToDesktop(2)
CapsLock & e::MoveCurrentWindowToDesktop(3)
CapsLock & r::MoveCurrentWindowToDesktop(4)
CapsLock & t::MoveCurrentWindowToDesktop(5)
CapsLock & y::MoveCurrentWindowToDesktop(6)
CapsLock & u::MoveCurrentWindowToDesktop(7)
CapsLock & i::MoveCurrentWindowToDesktop(8)
CapsLock & o::MoveCurrentWindowToDesktop(9)
```

(ah troubleshooting always making people go. Do You Think i'm stupid XD)

**Comment by dylanpjx** [comment]
I have the same issue, I haven't remapped anything, so it's still capsLock+ qwerty and it works like capslock + number instead of it's intended function.

**Comment by Elijas** [comment]
I currently can't test this, but I wonder what the result of deleting the
line with "switchDesktopByNumber" results in? Also what windows version
(build number) do you have?


MoveCurrentWindowToDesktop(desktopNumber) {
WinGet, activeHwnd, ID, A
DllCall(MoveWindowToDesktopNumberProc, UInt, activeHwnd, UInt,
desktopNumber - 1)
switchDesktopByNumber(desktopNumber)
}

**Comment by dylanpjx** [comment]
I commented out the switchDesktopByNumber lines, and the moveCurrentWindowToDesktop still doesn't work. Do I need to install the .dll file for it to work? Because that wasn't included in the installation readme.
I'm currently on Windows V1809, build 17763.529

**Comment by Elijas** [comment]
> I commented out the switchDesktopByNumber lines, and the moveCurrentWindowToDesktop still doesn't work. Do I need to install the .dll file for it to work? Because that wasn't included in the installation readme.
> I'm currently on Windows V1809, build 17763.529

`moveCurrentWindowToDesktop` is completed by the DLL, so you're correct to identify it as the most likely issue.

No, install is not needed because dll is loaded directly as a file. 

The script was tested with V1803, so it is likely the case that new Windows version broke the DLL.

**Comment by justinmklam** [comment]
Also facing this issue of being unable to move active windows to other desktops. Currently on Windows 1809 Build 17763.557.

**Comment by nchowning** [comment]
I'm having the same issue as of OS build 18362.207

**Comment by nchowning** [comment]
I pulled down the latest source for VirtualDesktopAccessor - https://github.com/Ciantic/VirtualDesktopAccessor - and built it. That resolved the issue for me

**Comment by Elijas** [comment]
@nchowning I'm glad to hear! Could you submit the dll via pull request?

**Comment by dylanpjx** [comment]
I think the github repo should include the building of the .dll as part of the readme, or at least link it to the virtualDesktopAccessor above. That would help in clarifying this issue since quite a few people seem to be confused about it. Cheers!

**Comment by pmb6tz** [comment]
Just pushed the requested change; fixed the issue for me. Give a try and let me know if it works for you as well. Thanks @nchowning !
