### ISSUE TITLE
Disabling the "Ctrl + Alt" combination

### ISSUE THREAD

**Issue by justmapping** [pmb6tz/windows-desktop-switcher#44]
Thanks a lot for your great tool that has been a lifesaver so far!

I was using a similar software that is no longer maintained.

Is there any way to disable the "Ctrl + Alt" feature described below?
_Using Ctrl + Alt instead of CapsLock also works, without any additional changes necessary (e.g. use <Ctrl> + <Alt> + 1 to switch to the Desktop 1, just as you would use <CapsLock> + 1)_

It keeps working even when disabling the CapsLock shortcut on the user_config.ahk file !
Many symbols require the "Alt Gr" (@, #, {) on FR keyboards.
Moreover "Ctrl + Alt" is equivalent to "Alt Gr" on such keyboards.
Therefore this default behavior is interfering a lot with my typing! 
Is there any way to disable it? 

You will see what I mean by referring to the AZERTY layout.

Many thanks!

**Comment by Elijas** [comment]
Do you have the latest copy of this repository downloaded? Ctrl Alt seems to be disabled now by default, I'll update the documentation to reflect this.

---

### How to enable/disable alternate configuration

In the `user_config.ahk` file, locate the lines like these (`^` means `<Ctrl>`, `!` means `Alt`):

https://github.com/pmb6tz/windows-desktop-switcher/blob/b0a8008d00300a41550dc26f98669d881c3e48c8/user_config.ahk#L58

#### 1a. How to enable a hotkey

Remove the `;` in the beginning of the hotkey lines, so the line looks like this

    ^!1::switchDesktopByNumber(1)

#### 1b. How to disable hotkey

Add the `;` in the beginning a of the hotkey lines, so the line looks like this

    ; ^!1::switchDesktopByNumber(1)

#### 2. Apply changes

After any changes be sure to start the program or reload if it's already running (click the tray icon with the right button and select `Reload`).

---

Let us know if this will help, or you'd have any more questions 👍

**Comment by justmapping** [comment]
Thanks a lot for the quick answer.

Indeed, the script I downloaded on Sunday seems to be an older one.
I replaced its content with that of the standalone file (link below) and it works fine.
https://raw.githubusercontent.com/pmb6tz/windows-desktop-switcher/master/desktop_switcher.ahk

I love your software so much that I was ready to re-map my keyboard again if needed.
https://superuser.com/questions/592970/can-i-make-ctrlalt-not-act-like-altgr-on-windows

Your documentation is extensive, and had enabled me to customize the user_config file already.
[user_config.txt](https://github.com/pmb6tz/windows-desktop-switcher/files/3517893/user_config.txt)

I was using Virtual Desktop Enhancer before. 
However, it no longer works since the latest Windows 10 update (author left the project).

Your program is more lightweight, and hopefully more robust.
I am using it with another older tool that shows the icons for each virtual desktop.
https://github.com/m0ngr31/VirtualDesktopManager
Combining both gets me all the features I need to enhance my productivity!

Hopefully we will be able to use it for as long as possible!
You guys are great. Thanks a lot for your excellent work.

**Comment by Elijas** [comment]
@justmapping I'm glad you've solved the issue and thank you for kind words! Much appreciated.

Regarding the tray icons, I've looked into it before and it would require more in-depth restructuring of code and testing + we think it may start to lose the lightwightness at this point, so I've left it out for now.

Let me know if there's any robustness bugs, as I've developed some quickfixes for the ones I've encountered, but I am not sure if they're related to this particular repo, so I've not publicized them yet.

Thanks again!

**Comment by Elijas** [comment]
Oh, and regarding the "working in the future", the only feature that at risk of this, is the one that uses the DLL - moving windows between desktops, other than that it should be well future-proofed

**Comment by justmapping** [comment]
Ok then thank you so much for going the extra mile with the DLL.
I use only 3 virtual desktops at most, and the ability to move windows across them is exactly why I love your program. 
That being said the .ahk scripts are so elegantly coded that I have no doubt you guys can also make it future-proof.

I was so desperate that I almost gave up looking for a native solution. 
Then I was saved by this comment: https://superuser.com/a/1253012

Right before that I even considered a non-native 3rd party solution (goScreen).
However such software is also intended for older versions of Windows (since 95), and of course tends to interfere quite a lot with the newer native virtual desktops feature (since Windows 10).

Thanks so much again
