### ISSUE TITLE
Shortcuts doesn't work when taskmanager is open.

### ISSUE THREAD

**Issue by AndeYashwanth** [pmb6tz/windows-desktop-switcher#48]
As the title says the shortcuts don't work when the task manager is open and the window is selected. Is this the restriction of windows? Can something be done about it?
Windows 10 1909.

**Comment by juhavt** [comment]
I guess it's because you would need admin rights to interact with the task manager window. Have you tried running your AutoHotkey script as admin? However, it may cause some unwanted behavior in some situations.

**Comment by AndeYashwanth** [comment]
Running the script as admin fixed this issue. Is there any way to automatically startup the script as admin?

**Comment by Elijas** [comment]
> Running the script as admin fixed this issue. Is there any way to automatically startup the script as admin?

Glad it got solved 🙂. Yes, you automatically run the script with admin privileges on boot, as described in README section [Running on boot (Administrator method)](https://github.com/pmb6tz/windows-desktop-switcher#advanced-administrator-method).

 Let us know if you'll have any more questions👍
