### ISSUE TITLE
The script behaves weirdly if you switch left when you are already at the leftmost desktop.

### ISSUE THREAD

**Issue by carbon-steel** [pmb6tz/windows-desktop-switcher#5]
I've noticed that, at the leftmost desktop, if you press the command for moving to the desktop to the left an odd number of times, the next command to shift to the desktop to the right does not do anything (but then the next command to move right works correctly). If you press the command for moving to the desktop to the left an even number of times (when you are at the leftmost desktop), the script works fine. I haven't tried it for the opposite situation (when you are one the right most desktop moving right), but I imagine it is the same case there.

**Comment by pmb6tz** [comment]
yeah, just validated that this happens.. I never use those hotkeys so didn't notice, but it definitely needs to be fixed. I'll look into it.
