### ISSUE TITLE
possible to use right and left arrows?

### ISSUE THREAD

**Issue by kalamalka** [pmb6tz/windows-desktop-switcher#57]
In autohotkey we usually have the ability to use left and right arrow keys. In the user config I have tried:

```
^{Right}::switchDesktopToRight()            
^{Left}::switchDesktopToLeft()
```

but getting error that these keys are not valid.

**Comment by Elijas** [comment]
Does 
`^Right::switchDesktopToRight()`    
work?

**Comment by kalamalka** [comment]
Thank you this worked! Is there support for changing the wallpaper for each individual desktop? There was another .AHK script out there that used to do this, but no longer works =(

**Comment by Elijas** [comment]
Glad to hear!
Let's continue discussion about wallpapers on [it's own issue](https://github.com/pmb6tz/windows-desktop-switcher/issues/58)
