### ISSUE TITLE
Change wallpaper on desktop switch

### ISSUE THREAD

**Issue by Elijas** [pmb6tz/windows-desktop-switcher#58]
Is there support for changing the wallpaper for each individual desktop? There was another .AHK script out there that used to do this, but no longer works =(

_Originally posted by @kalamalka in https://github.com/pmb6tz/windows-desktop-switcher/issues/57#issuecomment-625674736_

**Comment by Elijas** [comment]
Regarding wallpaper change, you're probably referring to [sdias/win-10-virtual-desktop-enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/virtual-desktop-enhancer.ahk#L539)

You could try to fix the other repository by overwriting their DLL with our DLL in their [libraries](https://github.com/sdias/win-10-virtual-desktop-enhancer/tree/master/libraries) folder.

Other solution could be to copy paste their solution to our script although that would require some coding knowledge

**Comment by kalamalka** [comment]
Thanks for moving this. Sorry to post in the wrong place. Yes, that was the AHK I was referring to. I have little knowledge of coding. How would I go about the DLL swap? Are you talking about simply renaming your DLL and placing it in their directory? How would this work ?

**Comment by Elijas** [comment]
No problem! Yes, you can just rename our DLL and overwrite their DLL, and it might help (because both of our repositories depend on the same DLL source, but we might have a newer version)

**Comment by kalamalka** [comment]
Oh My God it worked ! Thanks for this !

If only there was a way to get the preview windows (up at the top) to show the different wallpapers (i read somewhere this was in issue).

**Comment by Elijas** [comment]
Great!:) Agreed, it would be cool. Maybe it would be possible to do it with some coding, haven't tried yet
