### ISSUE TITLE
Anny way to make the desktop not also switch when moving an app to another desktop?

### ISSUE THREAD

**Issue by NicTanghe** [pmb6tz/windows-desktop-switcher#63]
Anny way to make the desktop not also switch when moving an app to another desktop?

**Comment by NicTanghe** [comment]
9 ive noticed that this already happens when using RH windows and alt.
my shortcut is #!1::MoveCurrentWindowToDesktop(1)

**Comment by Elijas** [comment]
Yes, all you need to do is to "comment out" the instruction that changes the desktop after moving the window. You can do this by adding a semicolon at the beginning of this line:

https://github.com/pmb6tz/windows-desktop-switcher/blob/36d1b3ed5ddaca16abedab703aeb07accf5f66f1/desktop_switcher.ahk#L195

so it looks like this:

```
;switchDesktopByNumber(desktopNumber)
```

To apply the changes, close the program and run it again.

Let us know if this works for you!

**Comment by NicTanghe** [comment]
It worked. thx
