### ISSUE TITLE
How to disable auto-cycles

### ISSUE THREAD

**Issue by exsabuta** [pmb6tz/windows-desktop-switcher#66]
Hi. Tell me please, how i can disable auto-cycles from the first to the last desktop?

**Comment by Elijas** [comment]
Hi! Thanks for asking.

Two lines are responsible for that. Switching desktop to right:
https://github.com/pmb6tz/windows-desktop-switcher/blob/755abfc8258f496714aaabce75c56a60ee75c850/desktop_switcher.ahk#L154
Switching desktop to left:
https://github.com/pmb6tz/windows-desktop-switcher/blob/755abfc8258f496714aaabce75c56a60ee75c850/desktop_switcher.ahk#L161

Change them to these, respectively:
```
_switchDesktopToTarget(CurrentDesktop == DesktopCount ? CurrentDesktop : CurrentDesktop + 1)
```
```
_switchDesktopToTarget(CurrentDesktop == 1 ? CurrentDesktop : CurrentDesktop - 1)
```

Then reload (shutdown and start again) the script again for the changes to be applied.

Please let us know if it works for you!

**Comment by exsabuta** [comment]
It works! Thanks!
