### ISSUE TITLE
how to disable CapsLock original function

### ISSUE THREAD

**Issue by makerjackie** [pmb6tz/windows-desktop-switcher#68]
I often touch CapsLock by mistake, so it switch to Capital, I want use CapsLock for switcher only, so how to disable CapsLock original function?

**Comment by Elijas** [comment]
Here is the solution:
https://github.com/pmb6tz/windows-desktop-switcher/issues/67#issuecomment-772791781

Let us know if it works for you

**Comment by makerjackie** [comment]
thx !!! it works
