### ISSUE TITLE
Windows 11 desktop number not tracking

### ISSUE THREAD

**Issue by Tylerwbrown** [pmb6tz/windows-desktop-switcher#74]
From what I can tell, it seems that the desktop number doesn't track when I use other means to change the desktop (like windows+ctrl+left/right), and it isn't updating from the normal registry point.

**Comment by Datamined** [comment]
I use Ctrl+Shift+{number} for switching and Ctrl+Alt+{number} for dragging. After update to Windows 11 switching doesn't work time to time and dragging just never works.

**Comment by Elijas** [comment]
Should be fixed now, thanks to @gorbunovav 🥳
