### ISSUE TITLE
AutoHotkey Version 2 breaks compatibility

### ISSUE THREAD

**Issue by ChristianHinge** [pmb6tz/windows-desktop-switcher#86]
Version 2.0 of AutoHotkey has officially been released, which, among other things, removes the "#NoEnv" command.  [version 2.0 changes](https://www.autohotkey.com/docs/v2/v2-changes.htm)   
When opening desktop_switcher.ahk, via AutoHotkey, you get an error saying:

`Error: This line does not contain a recognized action.`

I think the readme should be updated to state that version <2.0 is needed to run the project (until compatible comes back).

**Comment by rikrdo89** [comment]
Same issue here. Is there a workaround to make the script work with AHK v2.0?

**Comment by hexadeciman** [comment]
interested too !

**Comment by crossan007** [comment]
Also interested

**Comment by ChristianHinge** [comment]
If you install AutohotKey version 1, then it works fine.

**Comment by crossan007** [comment]
@ChristianHinge  yep, V1 works fine.

I opened #88  to add a header to the script so that anyone who tries running it with V2 will be prompted to auto-install and run with V1

**Comment by eriksneff** [comment]
Just finished installing Autohotkey v2.0.2 only to discover I had the wrong version. I then re-read the installation portion of this page https://github.com/pmb6tz/windows-desktop-switcher and realized there's a line that's misleading: 

```Install AutoHotkey v1.1 or later``` - this is technically incorrect and misleading.  Should 


Maybe something like this would be better:
```Install AutoHotkey Version 1 Only (v1.1 or later, but not version 2 or later)```
```Install AutoHotkey v1.1 or later but Not Version 2``` 
```Install AutoHotkey Verion X, where 1.1 => X < 2```


Actually kinda hard to say in an intuitive way, but one thing I'm confident about - it shouldn't say what it does now. Or better yet - add support for version 2!
