### ISSUE TITLE
No longer working with the new windows 11 update. Build 22621.2283

### ISSUE THREAD

**Issue by theb0ringdev** [pmb6tz/windows-desktop-switcher#94]
The script loads up but the actions do nothing. I am not sure what's wrong but I am pretty sure it's the new update. I hope the fix will be updated soon 🙏windows is a pain without this

**Comment by dbonner** [comment]
Hi @theb0ringdev @pmb6tz and @Elijas ,
Yes, I've got the same problem. It happens on both my desktop and my laptop. Windows-desktop-switcher was working perfectly until Windows Update installed Windows build 10.0.22621.2283. The script loads.  The shortcut keys do nothing now.  Nb: I am not using Windows Insider.  This was a normal Windows Update. All the best, Daniel

**Comment by paulyy-y** [comment]
Ditto.

**Comment by R-Bower** [comment]
I reverted the Windows update – really impacted my workflow.

**Comment by dbonner** [comment]
Hi all,
I found a fix:
Replace VirtualDesktopAccessor.dll in the root directory of windows-desktop-switcher with the newest dll from:
[https://github.com/Ciantic/VirtualDesktopAccessor/releases](url)
Now everything works again.
All the best, Daniel

**Comment by Elijas** [comment]
Hey everyone,

Big thanks to @dbonner for finding a solution to this issue. I've gone ahead and updated the main repository with the newest dll from the official source. This should help sort out the problem for those who've upgraded to the new Windows 11 update, build 22621.2283.

You can now grab the updated dll directly from our repository. If you run into any more issues, don't hesitate to reach out. Your feedback is super important in making this project better. Thanks for being such an awesome community!
